//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Cli.commands.list {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.DotNet.Cli.commands.list.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        public static string GlobalOptionDescription {
            get {
                return ResourceManager.GetString("GlobalOptionDescription", resourceCulture);
            }
        }
        
        public static string ToolPathOptionName {
            get {
                return ResourceManager.GetString("ToolPathOptionName", resourceCulture);
            }
        }
        
        public static string ToolPathOptionDescription {
            get {
                return ResourceManager.GetString("ToolPathOptionDescription", resourceCulture);
            }
        }
        
        public static string InvalidPackageWarning {
            get {
                return ResourceManager.GetString("InvalidPackageWarning", resourceCulture);
            }
        }
        
        public static string PackageIdColumn {
            get {
                return ResourceManager.GetString("PackageIdColumn", resourceCulture);
            }
        }
        
        public static string VersionColumn {
            get {
                return ResourceManager.GetString("VersionColumn", resourceCulture);
            }
        }
        
        public static string CommandsColumn {
            get {
                return ResourceManager.GetString("CommandsColumn", resourceCulture);
            }
        }
        
        public static string InvalidToolPathOption {
            get {
                return ResourceManager.GetString("InvalidToolPathOption", resourceCulture);
            }
        }
        
        public static string LocalOptionDescription {
            get {
                return ResourceManager.GetString("LocalOptionDescription", resourceCulture);
            }
        }
        
        public static string ListToolCommandInvalidGlobalAndLocalAndToolPath {
            get {
                return ResourceManager.GetString("ListToolCommandInvalidGlobalAndLocalAndToolPath", resourceCulture);
            }
        }
    }
}
