//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Cli {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLocalizableStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLocalizableStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.DotNet.Cli.CommonLocalizableStrings", typeof(CommonLocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UnsupportedProjectType {
            get {
                return ResourceManager.GetString("UnsupportedProjectType", resourceCulture);
            }
        }
        
        public static string ProjectAlreadyHasAreference {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasAreference", resourceCulture);
            }
        }
        
        public static string ProjectReferenceCouldNotBeFound {
            get {
                return ResourceManager.GetString("ProjectReferenceCouldNotBeFound", resourceCulture);
            }
        }
        
        public static string ProjectReferenceRemoved {
            get {
                return ResourceManager.GetString("ProjectReferenceRemoved", resourceCulture);
            }
        }
        
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        public static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        public static string ProjectReference {
            get {
                return ResourceManager.GetString("ProjectReference", resourceCulture);
            }
        }
        
        public static string ProjectReferenceOneOrMore {
            get {
                return ResourceManager.GetString("ProjectReferenceOneOrMore", resourceCulture);
            }
        }
        
        public static string PackageReference {
            get {
                return ResourceManager.GetString("PackageReference", resourceCulture);
            }
        }
        
        public static string P2P {
            get {
                return ResourceManager.GetString("P2P", resourceCulture);
            }
        }
        
        public static string P2PReference {
            get {
                return ResourceManager.GetString("P2PReference", resourceCulture);
            }
        }
        
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        public static string SolutionFile {
            get {
                return ResourceManager.GetString("SolutionFile", resourceCulture);
            }
        }
        
        public static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        public static string ReferenceAddedToTheProject {
            get {
                return ResourceManager.GetString("ReferenceAddedToTheProject", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        public static string XAddedToY {
            get {
                return ResourceManager.GetString("XAddedToY", resourceCulture);
            }
        }
        
        public static string XRemovedFromY {
            get {
                return ResourceManager.GetString("XRemovedFromY", resourceCulture);
            }
        }
        
        public static string XDeletedFromY {
            get {
                return ResourceManager.GetString("XDeletedFromY", resourceCulture);
            }
        }
        
        public static string XSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("XSuccessfullyUpdated", resourceCulture);
            }
        }
        
        public static string XIsInvalid {
            get {
                return ResourceManager.GetString("XIsInvalid", resourceCulture);
            }
        }
        
        public static string XYFoundButInvalid {
            get {
                return ResourceManager.GetString("XYFoundButInvalid", resourceCulture);
            }
        }
        
        public static string XFoundButInvalid {
            get {
                return ResourceManager.GetString("XFoundButInvalid", resourceCulture);
            }
        }
        
        public static string OperationInvalid {
            get {
                return ResourceManager.GetString("OperationInvalid", resourceCulture);
            }
        }
        
        public static string OperationXInvalid {
            get {
                return ResourceManager.GetString("OperationXInvalid", resourceCulture);
            }
        }
        
        public static string XNotFound {
            get {
                return ResourceManager.GetString("XNotFound", resourceCulture);
            }
        }
        
        public static string XOrYNotFound {
            get {
                return ResourceManager.GetString("XOrYNotFound", resourceCulture);
            }
        }
        
        public static string XOrYNotFoundInZ {
            get {
                return ResourceManager.GetString("XOrYNotFoundInZ", resourceCulture);
            }
        }
        
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        public static string XDoesNotExist {
            get {
                return ResourceManager.GetString("XDoesNotExist", resourceCulture);
            }
        }
        
        public static string XYDoesNotExist {
            get {
                return ResourceManager.GetString("XYDoesNotExist", resourceCulture);
            }
        }
        
        public static string MoreThanOneXFound {
            get {
                return ResourceManager.GetString("MoreThanOneXFound", resourceCulture);
            }
        }
        
        public static string XAlreadyContainsY {
            get {
                return ResourceManager.GetString("XAlreadyContainsY", resourceCulture);
            }
        }
        
        public static string XAlreadyContainsYZ {
            get {
                return ResourceManager.GetString("XAlreadyContainsYZ", resourceCulture);
            }
        }
        
        public static string XAlreadyHasY {
            get {
                return ResourceManager.GetString("XAlreadyHasY", resourceCulture);
            }
        }
        
        public static string XAlreadyHasYZ {
            get {
                return ResourceManager.GetString("XAlreadyHasYZ", resourceCulture);
            }
        }
        
        public static string XWasNotExpected {
            get {
                return ResourceManager.GetString("XWasNotExpected", resourceCulture);
            }
        }
        
        public static string XNotProvided {
            get {
                return ResourceManager.GetString("XNotProvided", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOne {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOne", resourceCulture);
            }
        }
        
        public static string CouldNotConnectWithTheServer {
            get {
                return ResourceManager.GetString("CouldNotConnectWithTheServer", resourceCulture);
            }
        }
        
        public static string RequiredArgumentIsInvalid {
            get {
                return ResourceManager.GetString("RequiredArgumentIsInvalid", resourceCulture);
            }
        }
        
        public static string OptionIsInvalid {
            get {
                return ResourceManager.GetString("OptionIsInvalid", resourceCulture);
            }
        }
        
        public static string ArgumentIsInvalid {
            get {
                return ResourceManager.GetString("ArgumentIsInvalid", resourceCulture);
            }
        }
        
        public static string RequiredArgumentNotPassed {
            get {
                return ResourceManager.GetString("RequiredArgumentNotPassed", resourceCulture);
            }
        }
        
        public static string RequiredCommandNotPassed {
            get {
                return ResourceManager.GetString("RequiredCommandNotPassed", resourceCulture);
            }
        }
        
        public static string CouldNotFindAnyProjectInDirectory {
            get {
                return ResourceManager.GetString("CouldNotFindAnyProjectInDirectory", resourceCulture);
            }
        }
        
        public static string CouldNotFindProjectOrDirectory {
            get {
                return ResourceManager.GetString("CouldNotFindProjectOrDirectory", resourceCulture);
            }
        }
        
        public static string MoreThanOneProjectInDirectory {
            get {
                return ResourceManager.GetString("MoreThanOneProjectInDirectory", resourceCulture);
            }
        }
        
        public static string FoundInvalidProject {
            get {
                return ResourceManager.GetString("FoundInvalidProject", resourceCulture);
            }
        }
        
        public static string InvalidProject {
            get {
                return ResourceManager.GetString("InvalidProject", resourceCulture);
            }
        }
        
        public static string InvalidProjectWithExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidProjectWithExceptionMessage", resourceCulture);
            }
        }
        
        public static string CouldNotFindSolutionIn {
            get {
                return ResourceManager.GetString("CouldNotFindSolutionIn", resourceCulture);
            }
        }
        
        public static string CouldNotFindSolutionOrDirectory {
            get {
                return ResourceManager.GetString("CouldNotFindSolutionOrDirectory", resourceCulture);
            }
        }
        
        public static string MoreThanOneSolutionInDirectory {
            get {
                return ResourceManager.GetString("MoreThanOneSolutionInDirectory", resourceCulture);
            }
        }
        
        public static string InvalidSolutionFormatString {
            get {
                return ResourceManager.GetString("InvalidSolutionFormatString", resourceCulture);
            }
        }
        
        public static string SolutionDoesNotExist {
            get {
                return ResourceManager.GetString("SolutionDoesNotExist", resourceCulture);
            }
        }
        
        public static string ReferenceIsInvalid {
            get {
                return ResourceManager.GetString("ReferenceIsInvalid", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOneReferenceToAdd {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneReferenceToAdd", resourceCulture);
            }
        }
        
        public static string PackageReferenceDoesNotExist {
            get {
                return ResourceManager.GetString("PackageReferenceDoesNotExist", resourceCulture);
            }
        }
        
        public static string PackageReferenceIsInvalid {
            get {
                return ResourceManager.GetString("PackageReferenceIsInvalid", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOnePackageReferenceToAdd {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOnePackageReferenceToAdd", resourceCulture);
            }
        }
        
        public static string PackageReferenceAddedToTheProject {
            get {
                return ResourceManager.GetString("PackageReferenceAddedToTheProject", resourceCulture);
            }
        }
        
        public static string ProjectAlreadyHasAPackageReference {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasAPackageReference", resourceCulture);
            }
        }
        
        public static string PleaseSpecifyVersion {
            get {
                return ResourceManager.GetString("PleaseSpecifyVersion", resourceCulture);
            }
        }
        
        public static string ProjectDoesNotExist {
            get {
                return ResourceManager.GetString("ProjectDoesNotExist", resourceCulture);
            }
        }
        
        public static string ProjectIsInvalid {
            get {
                return ResourceManager.GetString("ProjectIsInvalid", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOneProjectToAdd {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneProjectToAdd", resourceCulture);
            }
        }
        
        public static string ProjectAddedToTheSolution {
            get {
                return ResourceManager.GetString("ProjectAddedToTheSolution", resourceCulture);
            }
        }
        
        public static string ProjectRemovedFromTheSolution {
            get {
                return ResourceManager.GetString("ProjectRemovedFromTheSolution", resourceCulture);
            }
        }
        
        public static string SolutionAlreadyContainsProject {
            get {
                return ResourceManager.GetString("SolutionAlreadyContainsProject", resourceCulture);
            }
        }
        
        public static string ReferenceNotFoundInTheProject {
            get {
                return ResourceManager.GetString("ReferenceNotFoundInTheProject", resourceCulture);
            }
        }
        
        public static string ReferenceRemoved {
            get {
                return ResourceManager.GetString("ReferenceRemoved", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOneReferenceToRemove {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneReferenceToRemove", resourceCulture);
            }
        }
        
        public static string ReferenceDeleted {
            get {
                return ResourceManager.GetString("ReferenceDeleted", resourceCulture);
            }
        }
        
        public static string PackageReferenceNotFoundInTheProject {
            get {
                return ResourceManager.GetString("PackageReferenceNotFoundInTheProject", resourceCulture);
            }
        }
        
        public static string PackageReferenceRemoved {
            get {
                return ResourceManager.GetString("PackageReferenceRemoved", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOnePackageReferenceToRemove {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOnePackageReferenceToRemove", resourceCulture);
            }
        }
        
        public static string PackageReferenceDeleted {
            get {
                return ResourceManager.GetString("PackageReferenceDeleted", resourceCulture);
            }
        }
        
        public static string ProjectNotFoundInTheSolution {
            get {
                return ResourceManager.GetString("ProjectNotFoundInTheSolution", resourceCulture);
            }
        }
        
        public static string ProjectRemoved {
            get {
                return ResourceManager.GetString("ProjectRemoved", resourceCulture);
            }
        }
        
        public static string SpecifyAtLeastOneProjectToRemove {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneProjectToRemove", resourceCulture);
            }
        }
        
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        public static string NoReferencesFound {
            get {
                return ResourceManager.GetString("NoReferencesFound", resourceCulture);
            }
        }
        
        public static string NoProjectsFound {
            get {
                return ResourceManager.GetString("NoProjectsFound", resourceCulture);
            }
        }
        
        public static string ArgumentsProjectOrSolutionDescription {
            get {
                return ResourceManager.GetString("ArgumentsProjectOrSolutionDescription", resourceCulture);
            }
        }
        
        public static string ProjectArgumentName {
            get {
                return ResourceManager.GetString("ProjectArgumentName", resourceCulture);
            }
        }
        
        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }
        
        public static string CmdFramework {
            get {
                return ResourceManager.GetString("CmdFramework", resourceCulture);
            }
        }
        
        public static string PleaseSpecifyNewVersion {
            get {
                return ResourceManager.GetString("PleaseSpecifyNewVersion", resourceCulture);
            }
        }
        
        public static string PleaseSpecifyWhichPackageToUpdate {
            get {
                return ResourceManager.GetString("PleaseSpecifyWhichPackageToUpdate", resourceCulture);
            }
        }
        
        public static string NothingToUpdate {
            get {
                return ResourceManager.GetString("NothingToUpdate", resourceCulture);
            }
        }
        
        public static string EverythingUpToDate {
            get {
                return ResourceManager.GetString("EverythingUpToDate", resourceCulture);
            }
        }
        
        public static string PackageVersionUpdatedTo {
            get {
                return ResourceManager.GetString("PackageVersionUpdatedTo", resourceCulture);
            }
        }
        
        public static string PackageVersionUpdated {
            get {
                return ResourceManager.GetString("PackageVersionUpdated", resourceCulture);
            }
        }
        
        public static string CouldNotUpdateTheVersion {
            get {
                return ResourceManager.GetString("CouldNotUpdateTheVersion", resourceCulture);
            }
        }
        
        public static string TemplateCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TemplateCreatedSuccessfully", resourceCulture);
            }
        }
        
        public static string TemplateInstalledSuccesfully {
            get {
                return ResourceManager.GetString("TemplateInstalledSuccesfully", resourceCulture);
            }
        }
        
        public static string TemplateCreateError {
            get {
                return ResourceManager.GetString("TemplateCreateError", resourceCulture);
            }
        }
        
        public static string TemplateInstallError {
            get {
                return ResourceManager.GetString("TemplateInstallError", resourceCulture);
            }
        }
        
        public static string SpecifiedNameExists {
            get {
                return ResourceManager.GetString("SpecifiedNameExists", resourceCulture);
            }
        }
        
        public static string SpecifiedAliasExists {
            get {
                return ResourceManager.GetString("SpecifiedAliasExists", resourceCulture);
            }
        }
        
        public static string MandatoryParameterMissing {
            get {
                return ResourceManager.GetString("MandatoryParameterMissing", resourceCulture);
            }
        }
        
        public static string ProjectNotCompatibleWithFrameworks {
            get {
                return ResourceManager.GetString("ProjectNotCompatibleWithFrameworks", resourceCulture);
            }
        }
        
        public static string ProjectDoesNotTargetFramework {
            get {
                return ResourceManager.GetString("ProjectDoesNotTargetFramework", resourceCulture);
            }
        }
        
        public static string ProjectCouldNotBeEvaluated {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeEvaluated", resourceCulture);
            }
        }
        
        public static string VerbosityOptionDescription {
            get {
                return ResourceManager.GetString("VerbosityOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdVersionSuffixDescription {
            get {
                return ResourceManager.GetString("CmdVersionSuffixDescription", resourceCulture);
            }
        }
        
        public static string ShowHelpDescription {
            get {
                return ResourceManager.GetString("ShowHelpDescription", resourceCulture);
            }
        }
        
        public static string NoRestoreDescription {
            get {
                return ResourceManager.GetString("NoRestoreDescription", resourceCulture);
            }
        }
        
        public static string ToolSettingsInvalidXml {
            get {
                return ResourceManager.GetString("ToolSettingsInvalidXml", resourceCulture);
            }
        }
        
        public static string ToolSettingsMissingCommandName {
            get {
                return ResourceManager.GetString("ToolSettingsMissingCommandName", resourceCulture);
            }
        }
        
        public static string ToolSettingsMissingEntryPoint {
            get {
                return ResourceManager.GetString("ToolSettingsMissingEntryPoint", resourceCulture);
            }
        }
        
        public static string ToolSettingsInvalidCommandName {
            get {
                return ResourceManager.GetString("ToolSettingsInvalidCommandName", resourceCulture);
            }
        }
        
        public static string ToolSettingsMoreThanOneCommand {
            get {
                return ResourceManager.GetString("ToolSettingsMoreThanOneCommand", resourceCulture);
            }
        }
        
        public static string ToolSettingsUnsupportedRunner {
            get {
                return ResourceManager.GetString("ToolSettingsUnsupportedRunner", resourceCulture);
            }
        }
        
        public static string ShellShimConflict {
            get {
                return ResourceManager.GetString("ShellShimConflict", resourceCulture);
            }
        }
        
        public static string CannotCreateShimForEmptyExecutablePath {
            get {
                return ResourceManager.GetString("CannotCreateShimForEmptyExecutablePath", resourceCulture);
            }
        }
        
        public static string CannotCreateShimForEmptyCommand {
            get {
                return ResourceManager.GetString("CannotCreateShimForEmptyCommand", resourceCulture);
            }
        }
        
        public static string FailedToRetrieveToolConfiguration {
            get {
                return ResourceManager.GetString("FailedToRetrieveToolConfiguration", resourceCulture);
            }
        }
        
        public static string EnvironmentPathLinuxManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathLinuxManualInstructions", resourceCulture);
            }
        }
        
        public static string EnvironmentPathLinuxNeedLogout {
            get {
                return ResourceManager.GetString("EnvironmentPathLinuxNeedLogout", resourceCulture);
            }
        }
        
        public static string EnvironmentPathOSXManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathOSXManualInstructions", resourceCulture);
            }
        }
        
        public static string EnvironmentPathOSXNeedReopen {
            get {
                return ResourceManager.GetString("EnvironmentPathOSXNeedReopen", resourceCulture);
            }
        }
        
        public static string EnvironmentPathWindowsManualInstructions {
            get {
                return ResourceManager.GetString("EnvironmentPathWindowsManualInstructions", resourceCulture);
            }
        }
        
        public static string EnvironmentPathWindowsNeedReopen {
            get {
                return ResourceManager.GetString("EnvironmentPathWindowsNeedReopen", resourceCulture);
            }
        }
        
        public static string FailedToSetToolsPathEnvironmentVariable {
            get {
                return ResourceManager.GetString("FailedToSetToolsPathEnvironmentVariable", resourceCulture);
            }
        }
        
        public static string FailedToCreateShellShim {
            get {
                return ResourceManager.GetString("FailedToCreateShellShim", resourceCulture);
            }
        }
        
        public static string FailedToRemoveShellShim {
            get {
                return ResourceManager.GetString("FailedToRemoveShellShim", resourceCulture);
            }
        }
        
        public static string FailedSettingShimPermissions {
            get {
                return ResourceManager.GetString("FailedSettingShimPermissions", resourceCulture);
            }
        }
        
        public static string FailedToInstallToolPackage {
            get {
                return ResourceManager.GetString("FailedToInstallToolPackage", resourceCulture);
            }
        }
        
        public static string FailedToUninstallToolPackage {
            get {
                return ResourceManager.GetString("FailedToUninstallToolPackage", resourceCulture);
            }
        }
        
        public static string MissingToolEntryPointFile {
            get {
                return ResourceManager.GetString("MissingToolEntryPointFile", resourceCulture);
            }
        }
        
        public static string MissingToolSettingsFile {
            get {
                return ResourceManager.GetString("MissingToolSettingsFile", resourceCulture);
            }
        }
        
        public static string ToolPackageConflictPackageId {
            get {
                return ResourceManager.GetString("ToolPackageConflictPackageId", resourceCulture);
            }
        }
        
        public static string FailedToFindStagedToolPackage {
            get {
                return ResourceManager.GetString("FailedToFindStagedToolPackage", resourceCulture);
            }
        }
        
        public static string ColumnMaxWidthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ColumnMaxWidthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        public static string ToolSettingsInvalidLeadingDotCommandName {
            get {
                return ResourceManager.GetString("ToolSettingsInvalidLeadingDotCommandName", resourceCulture);
            }
        }
        
        public static string FormatVersionIsHigher {
            get {
                return ResourceManager.GetString("FormatVersionIsHigher", resourceCulture);
            }
        }
        
        public static string FormatVersionIsMalformed {
            get {
                return ResourceManager.GetString("FormatVersionIsMalformed", resourceCulture);
            }
        }
        
        public static string FormatVersionIsMissing {
            get {
                return ResourceManager.GetString("FormatVersionIsMissing", resourceCulture);
            }
        }
        
        public static string MoreThanOnePackagedShimAvailable {
            get {
                return ResourceManager.GetString("MoreThanOnePackagedShimAvailable", resourceCulture);
            }
        }
        
        public static string FailedToReadNuGetLockFile {
            get {
                return ResourceManager.GetString("FailedToReadNuGetLockFile", resourceCulture);
            }
        }
        
        public static string LevelArgumentName {
            get {
                return ResourceManager.GetString("LevelArgumentName", resourceCulture);
            }
        }
        
        public static string FrameworkArgumentName {
            get {
                return ResourceManager.GetString("FrameworkArgumentName", resourceCulture);
            }
        }
        
        public static string RuntimeIdentifierArgumentName {
            get {
                return ResourceManager.GetString("RuntimeIdentifierArgumentName", resourceCulture);
            }
        }
        
        public static string ConfigurationArgumentName {
            get {
                return ResourceManager.GetString("ConfigurationArgumentName", resourceCulture);
            }
        }
        
        public static string VersionSuffixArgumentName {
            get {
                return ResourceManager.GetString("VersionSuffixArgumentName", resourceCulture);
            }
        }
        
        public static string SolutionOrProjectArgumentDescription {
            get {
                return ResourceManager.GetString("SolutionOrProjectArgumentDescription", resourceCulture);
            }
        }
        
        public static string SolutionOrProjectArgumentName {
            get {
                return ResourceManager.GetString("SolutionOrProjectArgumentName", resourceCulture);
            }
        }
        
        public static string CommandInteractiveOptionDescription {
            get {
                return ResourceManager.GetString("CommandInteractiveOptionDescription", resourceCulture);
            }
        }
    }
}
