//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class DotnetToolMetadata
{

    private string commandNameField;

    private string toolAssemblyEntryPointField;

    /// <remarks/>
    public string CommandName
    {
        get
        {
            return this.commandNameField;
        }
        set
        {
            this.commandNameField = value;
        }
    }

    /// <remarks/>
    public string ToolAssemblyEntryPoint
    {
        get
        {
            return this.toolAssemblyEntryPointField;
        }
        set
        {
            this.toolAssemblyEntryPointField = value;
        }
    }
}
