//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Cli.commands {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.DotNet.Cli.commands.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppFullName {
            get {
                return ResourceManager.GetString("AppFullName", resourceCulture);
            }
        }
        
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        public static string CmdArgument {
            get {
                return ResourceManager.GetString("CmdArgument", resourceCulture);
            }
        }
        
        public static string CmdArgumentDescription {
            get {
                return ResourceManager.GetString("CmdArgumentDescription", resourceCulture);
            }
        }
        
        public static string CmdSourceOption {
            get {
                return ResourceManager.GetString("CmdSourceOption", resourceCulture);
            }
        }
        
        public static string CmdSourceOptionDescription {
            get {
                return ResourceManager.GetString("CmdSourceOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdRuntimeOption {
            get {
                return ResourceManager.GetString("CmdRuntimeOption", resourceCulture);
            }
        }
        
        public static string CmdRuntimeOptionDescription {
            get {
                return ResourceManager.GetString("CmdRuntimeOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdPackagesOption {
            get {
                return ResourceManager.GetString("CmdPackagesOption", resourceCulture);
            }
        }
        
        public static string CmdPackagesOptionDescription {
            get {
                return ResourceManager.GetString("CmdPackagesOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdDisableParallelOptionDescription {
            get {
                return ResourceManager.GetString("CmdDisableParallelOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdConfigFileOption {
            get {
                return ResourceManager.GetString("CmdConfigFileOption", resourceCulture);
            }
        }
        
        public static string CmdConfigFileOptionDescription {
            get {
                return ResourceManager.GetString("CmdConfigFileOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdNoCacheOptionDescription {
            get {
                return ResourceManager.GetString("CmdNoCacheOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdIgnoreFailedSourcesOptionDescription {
            get {
                return ResourceManager.GetString("CmdIgnoreFailedSourcesOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdNoDependenciesOptionDescription {
            get {
                return ResourceManager.GetString("CmdNoDependenciesOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdForceRestoreOptionDescription {
            get {
                return ResourceManager.GetString("CmdForceRestoreOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdLockedModeOptionDescription {
            get {
                return ResourceManager.GetString("CmdLockedModeOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdLockFilePathOption {
            get {
                return ResourceManager.GetString("CmdLockFilePathOption", resourceCulture);
            }
        }
        
        public static string CmdLockFilePathOptionDescription {
            get {
                return ResourceManager.GetString("CmdLockFilePathOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdReevaluateOptionDescription {
            get {
                return ResourceManager.GetString("CmdReevaluateOptionDescription", resourceCulture);
            }
        }
        
        public static string CmdUseLockFileOptionDescription {
            get {
                return ResourceManager.GetString("CmdUseLockFileOptionDescription", resourceCulture);
            }
        }
    }
}
